[workspace]
resolver = "2"
members = [
    "crates/midi-main"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
license = "MIT OR Apache-2.0"
authors = ["me"]
repository = "https://github.com/fruegger/mo-music"
description = "Reading and inspecting Standard MIDI Files"

[workspace.dependencies]
# intra-workspace

# shared external deps (kept in sync across crates)
thiserror = "1"

[profile.release]
lto = true
codegen-units = 1
strip = true